# Generated by Django 4.1.6 on 2023-04-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="click",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="conversion",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="notification", name="price", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="revenue",
            field=models.IntegerField(null=True),
        ),
    ]
